# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
