# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
